server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location = /index.html { add_header Cache-Control "no-cache"; }

  location /kolibri/ {
    proxy_pass https://capsule.kolibrigames.com/api/client/v1/;
    proxy_set_header Host capsule.kolibrigames.com;
    proxy_set_header Authorization $http_authorization;
    proxy_pass_header Authorization;
    proxy_ssl_server_name on;
    proxy_buffering off;
  }

  location /master/ {
    proxy_pass https://idle-miners.com/;
    proxy_set_header Host idle-miners.com;
    proxy_ssl_server_name on;
    proxy_buffering off;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
