import { useEffect, useMemo, useState } from "react";
import { getSyncMetadata, loadProgress, rankThreshold, saveProgress, setSyncMetadata, strengthScore, type CatalogManager, type PlayerManager, type SyncMetadata } from "./lib/db";
import { fetchKolibri, type KolibriCredentials, type KolibriDiagnostics } from "./lib/kolibri";

type Tab = "today" | "managers" | "strategy" | "more";
const areas = ["Mine Shaft", "Elevator", "Warehouse"];

export default function App() {
  const [catalog, setCatalog] = useState<CatalogManager[]>([]);
  const [progress, setProgress] = useState<PlayerManager[]>([]);
  const [metadata, setMetadata] = useState<SyncMetadata>({ status: "never" });
  const [tab, setTab] = useState<Tab>("today");
  const [query, setQuery] = useState("");
  const [area, setArea] = useState("All");
  const [ownership, setOwnership] = useState<"unlocked" | "all">("unlocked");
  const [selected, setSelected] = useState<CatalogManager | null>(null);
  const [syncing, setSyncing] = useState(false);
  const [credentials, setCredentials] = useState<KolibriCredentials>({ kolibriId: import.meta.env.VITE_KOLIBRI_ID ?? "", authToken: import.meta.env.VITE_KOLIBRI_AUTH_TOKEN ?? "", saveGameKey: import.meta.env.VITE_KOLIBRI_SAVE_GAME_KEY ?? "0" });
  const [diagnostics, setDiagnostics] = useState<KolibriDiagnostics | null>(null);

  useEffect(() => { void (async () => { const response = await fetch("/catalog/sm_complete_database.json"); const json = await response.json() as { managers: CatalogManager[] }; let managers = json.managers; try { const remote = await (await fetch("/master/api/sm-data")).json() as Array<CatalogManager & { gameId: number }>; if (Array.isArray(remote) && remote.length) { const byId = new Map(remote.map((item) => [item.id, item])); managers = managers.map((item) => ({ ...item, ...(byId.get(item.id) ?? {}) })); } } catch { /* bundled catalog remains usable offline */ } setCatalog(managers); setProgress(await loadProgress(managers)); setMetadata(await getSyncMetadata()); })(); }, []);
  const byId = useMemo(() => new Map(catalog.map((m) => [m.id, m])), [catalog]);
  const unlocked = progress.filter((p) => p.unlocked);
  const managers = useMemo(() => progress.map((p) => ({ ...p, catalog: byId.get(p.managerId) })).filter((p): p is PlayerManager & { catalog: CatalogManager } => Boolean(p.catalog)).filter((p) => ownership === "all" || p.unlocked).filter((p) => area === "All" || p.catalog.type === area).filter((p) => !query || p.catalog.name.toLowerCase().includes(query.toLowerCase())).sort((a, b) => strengthScore(b.catalog, b) - strengthScore(a.catalog, a) || a.catalog.name.localeCompare(b.catalog.name)), [progress, byId, ownership, area, query]);
  const strongest = areas.map((name) => managers.filter((m) => m.unlocked && m.catalog.type === name)[0]).filter(Boolean);
  const opportunities = unlocked.map((p) => ({ p, m: byId.get(p.managerId)! })).filter(({ p }) => p.fragments > 0).sort((a, b) => b.p.fragments - a.p.fragments).slice(0, 4);

  async function syncNow() { setSyncing(true); const attemptedAt = new Date().toISOString(); try { if (!navigator.onLine) throw new Error("Offline — connect to the internet before syncing Kolibri."); const result = await fetchKolibri(credentials, catalog); await saveProgress(result.progress); setProgress(result.progress); setDiagnostics(result.diagnostics); const next: SyncMetadata = { ...metadata, lastAttemptAt: attemptedAt, lastSuccessfulSyncAt: attemptedAt, source: "Kolibri Capsule", status: "current" }; await setSyncMetadata(next); setMetadata(next); } catch (error) { const next: SyncMetadata = { ...metadata, lastAttemptAt: attemptedAt, status: navigator.onLine ? "stale" : "offline", error: error instanceof Error ? error.message : "Kolibri sync failed" }; await setSyncMetadata(next); setMetadata(next); } finally { setSyncing(false); } }
  useEffect(() => { if (catalog.length && credentials.kolibriId && credentials.authToken && metadata.status === "never") void syncNow(); }, [catalog.length]);
  async function updateManager(p: PlayerManager, patch: Partial<PlayerManager>) { const next = progress.map((item) => item.managerId === p.managerId ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item); setProgress(next); await saveProgress(next); }
  const freshness = metadata.status === "never" ? "No player data imported" : metadata.error ? `Sync error · ${metadata.error}` : metadata.status === "offline" ? "Offline · showing cached data" : metadata.lastSuccessfulSyncAt ? `Synced ${new Date(metadata.lastSuccessfulSyncAt).toLocaleString()}` : "Sync pending";

  return <main><header><div><p className="eyebrow">MINEOPS</p><h1>{tab === "today" ? "Today" : tab[0].toUpperCase() + tab.slice(1)}</h1></div><button onClick={() => void syncNow()}>{syncing ? "Syncing…" : "Sync Now"}</button></header><p className="status" role="status">{freshness}</p>
    {tab === "today" && <><section className="hero"><h2>{unlocked.length} unlocked of {catalog.length || "—"}</h2><p>Your catalog and player progress stay available offline. Import from Kolibri in More to refresh authoritative data.</p></section><section className="metrics"><div><strong>{unlocked.length}</strong><span>unlocked</span></div><div><strong>{opportunities.length}</strong><span>fragment opportunities</span></div><div><strong>{strongest.length}</strong><span>areas covered</span></div></section><section className="card"><h2>Strongest by area</h2>{strongest.length ? strongest.map((item) => <p key={item.managerId}><b>{item.catalog.type}</b> · {item.catalog.name} <span className="muted">Level {item.level} · Rank {item.rank}</span></p>) : <p className="muted">Import player data to see recommendations.</p>}</section><section className="card"><h2>Ready to improve</h2>{opportunities.length ? opportunities.map(({ p, m }) => <p key={p.managerId}><b>{m.name}</b> · {p.fragments} fragments {rankThreshold(p.rank) ? `of ${rankThreshold(p.rank)}` : ""}</p>) : <p className="muted">No fragment-backed opportunities yet.</p>}</section></>}
    {tab === "managers" && <><div className="toolbar"><input aria-label="Search managers" placeholder="Search managers" value={query} onChange={(e) => setQuery(e.target.value)} /><select value={ownership} onChange={(e) => setOwnership(e.target.value as "unlocked" | "all")}><option value="unlocked">Unlocked</option><option value="all">All managers</option></select><select value={area} onChange={(e) => setArea(e.target.value)}><option>All</option>{areas.map((name) => <option key={name}>{name}</option>)}</select></div><section className="grid">{managers.map((item) => <button className="manager-card" key={item.managerId} onClick={() => setSelected(item.catalog)}><span className={`rarity ${item.catalog.rarity.toLowerCase()}`}>{item.catalog.rarity}</span><h2>{item.catalog.name}</h2><p>{item.catalog.type}</p><small>{item.unlocked ? `Level ${item.level} · Rank ${item.rank} · ${item.fragments} fragments` : "Locked"}</small></button>)}</section></>}
    {tab === "strategy" && <section className="card"><h2>Strategy planner</h2>{unlocked.length >= 2 ? <><p>Rules-first lineup from your owned roster:</p><ol>{managers.slice(0, 3).map((item, index) => <li key={item.managerId}>Phase {index + 1}: {item.catalog.name} ({item.catalog.type})</li>)}</ol><p className="muted">Recommendations are deterministic and limited to imported managers.</p></> : <p className="muted">Import player data and unlock at least two managers to build a strategy.</p>}</section>}
    {tab === "more" && <><section className="card"><h2>Kolibri sync</h2><p>{freshness}</p><label>Kolibri ID or full debug string<input value={credentials.kolibriId} onChange={(e) => setCredentials({ ...credentials, kolibriId: e.target.value })} placeholder="Paste UUID/debug ID" /></label><label>Auth token<input type="password" value={credentials.authToken} onChange={(e) => setCredentials({ ...credentials, authToken: e.target.value })} placeholder="Token value" /></label><label>Save game key<input value={credentials.saveGameKey} onChange={(e) => setCredentials({ ...credentials, saveGameKey: e.target.value })} placeholder="0" /></label><button onClick={() => void syncNow()}>{syncing ? "Syncing…" : "Sync Now"}</button>{diagnostics && <p className="muted">{diagnostics.managerCount} managers received · {diagnostics.payloadFormat} · {diagnostics.unknownManagerCount} unmatched catalog IDs</p>}<p className="muted">Local development only. Credentials are held in this browser session unless provided through `.env`; never commit real values.</p></section><section className="card"><h2>About this build</h2><p>MineOpsWeb uses the verified Idle Miner Tycoon manager catalog ({catalog.length || "…"} records) and keeps catalog definitions separate from player state.</p></section></>}
    <nav aria-label="Primary">{(["today", "managers", "strategy", "more"] as Tab[]).map((item) => <button key={item} aria-current={tab === item ? "page" : undefined} onClick={() => setTab(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    {selected && <div className="dialog-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="dialog" onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setSelected(null)} aria-label="Close manager details">×</button><span className={`rarity ${selected.rarity.toLowerCase()}`}>{selected.rarity}</span><h2>{selected.name}</h2><p>{selected.type} · {selected.elements.join(" · ") || "No elements listed"}</p><h3>Active</h3><p>{selected.active?.description ?? "No active description"}</p><h3>Passives</h3>{selected.passives?.length ? selected.passives.map((passive, i) => <p key={i}>{passive.description ?? "Passive"}</p>) : <p className="muted">No passive data</p>}<button className="primary" onClick={() => { const p = progress.find((item) => item.managerId === selected.id); if (p) void updateManager(p, { unlocked: !p.unlocked }); }}>Toggle ownership</button></article></div>}
  </main>;
}
